### ISSUE TITLE
ak command may fail with Python3 on Ubuntu

### ISSUE THREAD

**Issue by rvalyi** [akretion/ak#55]
with Ubuntu Bionic and ak install via sudo pip3 install, I get this error:

```
erp@ns352692:~/docky-project1/odoo$ ak build
Traceback (most recent call last):
  File "/usr/local/bin/ak", line 11, in <module>
    load_entry_point('ak==2.0.4', 'console_scripts', 'ak')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/ak/__init__.py", line 9, in <module>
    from . import ak_build
  File "/usr/local/lib/python3.6/dist-packages/ak/ak_build.py", line 5, in <module>
    from plumbum.cmd import (
ImportError: cannot import name 'python'
```

workaround: edit usr/local/lib/python3.6/dist-packages/ak/ak_build.py and replacing `python` by `python3` at line 5.

**Comment by bealdav** [comment]
Probably by recent versions of pip

I propose to close it @rvalyi ?

**Comment by rvalyi** [comment]
yes I think it's closed.
